models:
  - name: gold_ticket_metrics
    description: "Aggregated metrics representing the total tickets and revenue by violation code."
    columns:
      - name: violation_code
        description: '{{ doc("violation_code") }}'
      - name: ticket_count
        description: '{{ doc("ticket_count") }}'
      - name: total_revenue_usd
        description: '{{ doc("total_revenue_usd") }}'

  - name: gold_vehicles_metrics
    description: "Aggregated metrics detailing the number of tickets per vehicle, identified by the plate ID."
    columns:
      - name: registration_state
        description: '{{ doc("registration_state") }}'
      - name: ticket_count
        description: '{{ doc("ticket_count") }}'

  - name: gold_employee_thirty_plus
    description: Stores total thirty plus employee information
    columns:
      - name: total_thirty_plus_employee
        description: Shows the count of total thirty plus employee
